

services:
  ai:
    build:
      dockerfile: /Users/lazarzivanovic/Desktop/chat_with_yt_video/microservice/Dockerfile
    image: ai
    container_name: ai
    ports:
      - 8000:8000
    environment:
      GEMINI_API_KEY: ADD API KEY
      NEO4J_PASSWORD: password
      NEO4J_USER: neo4j
      NEO4J_URL: bolt://neo4j:7687
      BE_URL: http://be:8080/api
    depends_on:
      - neo4j 

  be:
    build: 
      dockerfile: /Users/lazarzivanovic/Desktop/chat_with_yt_video/app/Dockerfile
    container_name: be
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/talkie
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      ENV: dev
      AI_URL: http://ai:8000/api
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: talkie 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:2025.06.0
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687" 
    environment:
      - NEO4J_AUTH=none 
      - NEO4J_PLUGINS='["apoc"]' 
    volumes:
      - neo4j_data:/data

volumes:
  postgres_data:
    driver: local
  neo4j_data:
    driver: local